// I don't want to annoy github with constant requests, so I can work with example data from a pull
const example_data = {
	"login": "asa-dillahunty",
	"id": 28574798,
	"node_id": "MDQ6VXNlcjI4NTc0Nzk4",
	"avatar_url": "https://avatars.githubusercontent.com/u/28574798?v=4",
	"gravatar_id": "",
	"url": "https://api.github.com/users/asa-dillahunty",
	"html_url": "https://github.com/asa-dillahunty",
	"followers_url": "https://api.github.com/users/asa-dillahunty/followers",
	"following_url": "https://api.github.com/users/asa-dillahunty/following{/other_user}",
	"gists_url": "https://api.github.com/users/asa-dillahunty/gists{/gist_id}",
	"starred_url": "https://api.github.com/users/asa-dillahunty/starred{/owner}{/repo}",
	"subscriptions_url": "https://api.github.com/users/asa-dillahunty/subscriptions",
	"organizations_url": "https://api.github.com/users/asa-dillahunty/orgs",
	"repos_url": "https://api.github.com/users/asa-dillahunty/repos",
	"events_url": "https://api.github.com/users/asa-dillahunty/events{/privacy}",
	"received_events_url": "https://api.github.com/users/asa-dillahunty/received_events",
	"type": "User",
	"site_admin": false,
	"name": "Asa Dillahunty",
	"company": null,
	"blog": "",
	"location": null,
	"email": null,
	"hireable": true,
	"bio": null,
	"twitter_username": null,
	"public_repos": 8,
	"public_gists": 0,
	"followers": 0,
	"following": 2,
	"created_at": "2017-05-09T18:56:06Z",
	"updated_at": "2021-05-24T17:51:06Z"
}

const example_data2 = [
	{
	  "id": 286644814,
	  "node_id": "MDEwOlJlcG9zaXRvcnkyODY2NDQ4MTQ=",
	  "name": "asa-dillahunty",
	  "full_name": "asa-dillahunty/asa-dillahunty",
	  "private": false,
	  "owner": {
		"login": "asa-dillahunty",
		"id": 28574798,
		"node_id": "MDQ6VXNlcjI4NTc0Nzk4",
		"avatar_url": "https://avatars.githubusercontent.com/u/28574798?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/asa-dillahunty",
		"html_url": "https://github.com/asa-dillahunty",
		"followers_url": "https://api.github.com/users/asa-dillahunty/followers",
		"following_url": "https://api.github.com/users/asa-dillahunty/following{/other_user}",
		"gists_url": "https://api.github.com/users/asa-dillahunty/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/asa-dillahunty/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/asa-dillahunty/subscriptions",
		"organizations_url": "https://api.github.com/users/asa-dillahunty/orgs",
		"repos_url": "https://api.github.com/users/asa-dillahunty/repos",
		"events_url": "https://api.github.com/users/asa-dillahunty/events{/privacy}",
		"received_events_url": "https://api.github.com/users/asa-dillahunty/received_events",
		"type": "User",
		"site_admin": false
	  },
	  "html_url": "https://github.com/asa-dillahunty/asa-dillahunty",
	  "description": null,
	  "fork": false,
	  "url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty",
	  "forks_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/forks",
	  "keys_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/keys{/key_id}",
	  "collaborators_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/collaborators{/collaborator}",
	  "teams_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/teams",
	  "hooks_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/hooks",
	  "issue_events_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/issues/events{/number}",
	  "events_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/events",
	  "assignees_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/assignees{/user}",
	  "branches_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/branches{/branch}",
	  "tags_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/tags",
	  "blobs_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/git/blobs{/sha}",
	  "git_tags_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/git/tags{/sha}",
	  "git_refs_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/git/refs{/sha}",
	  "trees_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/git/trees{/sha}",
	  "statuses_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/statuses/{sha}",
	  "languages_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/languages",
	  "stargazers_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/stargazers",
	  "contributors_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/contributors",
	  "subscribers_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/subscribers",
	  "subscription_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/subscription",
	  "commits_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/commits{/sha}",
	  "git_commits_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/git/commits{/sha}",
	  "comments_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/comments{/number}",
	  "issue_comment_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/issues/comments{/number}",
	  "contents_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/contents/{+path}",
	  "compare_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/compare/{base}...{head}",
	  "merges_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/merges",
	  "archive_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/{archive_format}{/ref}",
	  "downloads_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/downloads",
	  "issues_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/issues{/number}",
	  "pulls_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/pulls{/number}",
	  "milestones_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/milestones{/number}",
	  "notifications_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/notifications{?since,all,participating}",
	  "labels_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/labels{/name}",
	  "releases_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/releases{/id}",
	  "deployments_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty/deployments",
	  "created_at": "2020-08-11T04:25:00Z",
	  "updated_at": "2020-08-11T21:03:57Z",
	  "pushed_at": "2020-08-11T21:03:55Z",
	  "git_url": "git://github.com/asa-dillahunty/asa-dillahunty.git",
	  "ssh_url": "git@github.com:asa-dillahunty/asa-dillahunty.git",
	  "clone_url": "https://github.com/asa-dillahunty/asa-dillahunty.git",
	  "svn_url": "https://github.com/asa-dillahunty/asa-dillahunty",
	  "homepage": null,
	  "size": 8,
	  "stargazers_count": 0,
	  "watchers_count": 0,
	  "language": null,
	  "has_issues": true,
	  "has_projects": true,
	  "has_downloads": true,
	  "has_wiki": true,
	  "has_pages": false,
	  "forks_count": 0,
	  "mirror_url": null,
	  "archived": false,
	  "disabled": false,
	  "open_issues_count": 0,
	  "license": null,
	  "forks": 0,
	  "open_issues": 0,
	  "watchers": 0,
	  "default_branch": "master"
	},
	{
	  "id": 215906950,
	  "node_id": "MDEwOlJlcG9zaXRvcnkyMTU5MDY5NTA=",
	  "name": "asa-dillahunty.github.io",
	  "full_name": "asa-dillahunty/asa-dillahunty.github.io",
	  "private": false,
	  "owner": {
		"login": "asa-dillahunty",
		"id": 28574798,
		"node_id": "MDQ6VXNlcjI4NTc0Nzk4",
		"avatar_url": "https://avatars.githubusercontent.com/u/28574798?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/asa-dillahunty",
		"html_url": "https://github.com/asa-dillahunty",
		"followers_url": "https://api.github.com/users/asa-dillahunty/followers",
		"following_url": "https://api.github.com/users/asa-dillahunty/following{/other_user}",
		"gists_url": "https://api.github.com/users/asa-dillahunty/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/asa-dillahunty/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/asa-dillahunty/subscriptions",
		"organizations_url": "https://api.github.com/users/asa-dillahunty/orgs",
		"repos_url": "https://api.github.com/users/asa-dillahunty/repos",
		"events_url": "https://api.github.com/users/asa-dillahunty/events{/privacy}",
		"received_events_url": "https://api.github.com/users/asa-dillahunty/received_events",
		"type": "User",
		"site_admin": false
	  },
	  "html_url": "https://github.com/asa-dillahunty/asa-dillahunty.github.io",
	  "description": "Personal Website",
	  "fork": false,
	  "url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io",
	  "forks_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/forks",
	  "keys_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/keys{/key_id}",
	  "collaborators_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/collaborators{/collaborator}",
	  "teams_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/teams",
	  "hooks_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/hooks",
	  "issue_events_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/issues/events{/number}",
	  "events_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/events",
	  "assignees_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/assignees{/user}",
	  "branches_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/branches{/branch}",
	  "tags_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/tags",
	  "blobs_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/git/blobs{/sha}",
	  "git_tags_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/git/tags{/sha}",
	  "git_refs_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/git/refs{/sha}",
	  "trees_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/git/trees{/sha}",
	  "statuses_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/statuses/{sha}",
	  "languages_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/languages",
	  "stargazers_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/stargazers",
	  "contributors_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/contributors",
	  "subscribers_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/subscribers",
	  "subscription_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/subscription",
	  "commits_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/commits{/sha}",
	  "git_commits_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/git/commits{/sha}",
	  "comments_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/comments{/number}",
	  "issue_comment_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/issues/comments{/number}",
	  "contents_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/contents/{+path}",
	  "compare_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/compare/{base}...{head}",
	  "merges_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/merges",
	  "archive_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/{archive_format}{/ref}",
	  "downloads_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/downloads",
	  "issues_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/issues{/number}",
	  "pulls_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/pulls{/number}",
	  "milestones_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/milestones{/number}",
	  "notifications_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/notifications{?since,all,participating}",
	  "labels_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/labels{/name}",
	  "releases_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/releases{/id}",
	  "deployments_url": "https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/deployments",
	  "created_at": "2019-10-18T00:04:16Z",
	  "updated_at": "2021-05-08T20:49:57Z",
	  "pushed_at": "2021-05-08T20:49:53Z",
	  "git_url": "git://github.com/asa-dillahunty/asa-dillahunty.github.io.git",
	  "ssh_url": "git@github.com:asa-dillahunty/asa-dillahunty.github.io.git",
	  "clone_url": "https://github.com/asa-dillahunty/asa-dillahunty.github.io.git",
	  "svn_url": "https://github.com/asa-dillahunty/asa-dillahunty.github.io",
	  "homepage": null,
	  "size": 145490,
	  "stargazers_count": 1,
	  "watchers_count": 1,
	  "language": "HTML",
	  "has_issues": true,
	  "has_projects": true,
	  "has_downloads": true,
	  "has_wiki": true,
	  "has_pages": true,
	  "forks_count": 0,
	  "mirror_url": null,
	  "archived": false,
	  "disabled": false,
	  "open_issues_count": 0,
	  "license": null,
	  "forks": 0,
	  "open_issues": 0,
	  "watchers": 1,
	  "default_branch": "master"
	},
	{
	  "id": 207968008,
	  "node_id": "MDEwOlJlcG9zaXRvcnkyMDc5NjgwMDg=",
	  "name": "CS201-Data-Structures-Library",
	  "full_name": "asa-dillahunty/CS201-Data-Structures-Library",
	  "private": false,
	  "owner": {
		"login": "asa-dillahunty",
		"id": 28574798,
		"node_id": "MDQ6VXNlcjI4NTc0Nzk4",
		"avatar_url": "https://avatars.githubusercontent.com/u/28574798?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/asa-dillahunty",
		"html_url": "https://github.com/asa-dillahunty",
		"followers_url": "https://api.github.com/users/asa-dillahunty/followers",
		"following_url": "https://api.github.com/users/asa-dillahunty/following{/other_user}",
		"gists_url": "https://api.github.com/users/asa-dillahunty/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/asa-dillahunty/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/asa-dillahunty/subscriptions",
		"organizations_url": "https://api.github.com/users/asa-dillahunty/orgs",
		"repos_url": "https://api.github.com/users/asa-dillahunty/repos",
		"events_url": "https://api.github.com/users/asa-dillahunty/events{/privacy}",
		"received_events_url": "https://api.github.com/users/asa-dillahunty/received_events",
		"type": "User",
		"site_admin": false
	  },
	  "html_url": "https://github.com/asa-dillahunty/CS201-Data-Structures-Library",
	  "description": "CS 201 Data Structures Library",
	  "fork": false,
	  "url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library",
	  "forks_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/forks",
	  "keys_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/keys{/key_id}",
	  "collaborators_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/collaborators{/collaborator}",
	  "teams_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/teams",
	  "hooks_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/hooks",
	  "issue_events_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/issues/events{/number}",
	  "events_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/events",
	  "assignees_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/assignees{/user}",
	  "branches_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/branches{/branch}",
	  "tags_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/tags",
	  "blobs_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/git/blobs{/sha}",
	  "git_tags_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/git/tags{/sha}",
	  "git_refs_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/git/refs{/sha}",
	  "trees_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/git/trees{/sha}",
	  "statuses_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/statuses/{sha}",
	  "languages_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/languages",
	  "stargazers_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/stargazers",
	  "contributors_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/contributors",
	  "subscribers_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/subscribers",
	  "subscription_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/subscription",
	  "commits_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/commits{/sha}",
	  "git_commits_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/git/commits{/sha}",
	  "comments_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/comments{/number}",
	  "issue_comment_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/issues/comments{/number}",
	  "contents_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/contents/{+path}",
	  "compare_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/compare/{base}...{head}",
	  "merges_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/merges",
	  "archive_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/{archive_format}{/ref}",
	  "downloads_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/downloads",
	  "issues_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/issues{/number}",
	  "pulls_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/pulls{/number}",
	  "milestones_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/milestones{/number}",
	  "notifications_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/notifications{?since,all,participating}",
	  "labels_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/labels{/name}",
	  "releases_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/releases{/id}",
	  "deployments_url": "https://api.github.com/repos/asa-dillahunty/CS201-Data-Structures-Library/deployments",
	  "created_at": "2019-09-12T04:58:02Z",
	  "updated_at": "2020-03-06T19:46:03Z",
	  "pushed_at": "2020-03-06T19:46:02Z",
	  "git_url": "git://github.com/asa-dillahunty/CS201-Data-Structures-Library.git",
	  "ssh_url": "git@github.com:asa-dillahunty/CS201-Data-Structures-Library.git",
	  "clone_url": "https://github.com/asa-dillahunty/CS201-Data-Structures-Library.git",
	  "svn_url": "https://github.com/asa-dillahunty/CS201-Data-Structures-Library",
	  "homepage": null,
	  "size": 763,
	  "stargazers_count": 0,
	  "watchers_count": 0,
	  "language": "C++",
	  "has_issues": true,
	  "has_projects": true,
	  "has_downloads": true,
	  "has_wiki": true,
	  "has_pages": false,
	  "forks_count": 0,
	  "mirror_url": null,
	  "archived": false,
	  "disabled": false,
	  "open_issues_count": 0,
	  "license": null,
	  "forks": 0,
	  "open_issues": 0,
	  "watchers": 0,
	  "default_branch": "master"
	},
	{
	  "id": 250730987,
	  "node_id": "MDEwOlJlcG9zaXRvcnkyNTA3MzA5ODc=",
	  "name": "CS300-Project",
	  "full_name": "asa-dillahunty/CS300-Project",
	  "private": false,
	  "owner": {
		"login": "asa-dillahunty",
		"id": 28574798,
		"node_id": "MDQ6VXNlcjI4NTc0Nzk4",
		"avatar_url": "https://avatars.githubusercontent.com/u/28574798?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/asa-dillahunty",
		"html_url": "https://github.com/asa-dillahunty",
		"followers_url": "https://api.github.com/users/asa-dillahunty/followers",
		"following_url": "https://api.github.com/users/asa-dillahunty/following{/other_user}",
		"gists_url": "https://api.github.com/users/asa-dillahunty/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/asa-dillahunty/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/asa-dillahunty/subscriptions",
		"organizations_url": "https://api.github.com/users/asa-dillahunty/orgs",
		"repos_url": "https://api.github.com/users/asa-dillahunty/repos",
		"events_url": "https://api.github.com/users/asa-dillahunty/events{/privacy}",
		"received_events_url": "https://api.github.com/users/asa-dillahunty/received_events",
		"type": "User",
		"site_admin": false
	  },
	  "html_url": "https://github.com/asa-dillahunty/CS300-Project",
	  "description": "Threading Project",
	  "fork": false,
	  "url": "https://api.github.com/repos/asa-dillahunty/CS300-Project",
	  "forks_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/forks",
	  "keys_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/keys{/key_id}",
	  "collaborators_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/collaborators{/collaborator}",
	  "teams_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/teams",
	  "hooks_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/hooks",
	  "issue_events_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/issues/events{/number}",
	  "events_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/events",
	  "assignees_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/assignees{/user}",
	  "branches_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/branches{/branch}",
	  "tags_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/tags",
	  "blobs_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/git/blobs{/sha}",
	  "git_tags_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/git/tags{/sha}",
	  "git_refs_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/git/refs{/sha}",
	  "trees_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/git/trees{/sha}",
	  "statuses_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/statuses/{sha}",
	  "languages_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/languages",
	  "stargazers_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/stargazers",
	  "contributors_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/contributors",
	  "subscribers_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/subscribers",
	  "subscription_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/subscription",
	  "commits_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/commits{/sha}",
	  "git_commits_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/git/commits{/sha}",
	  "comments_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/comments{/number}",
	  "issue_comment_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/issues/comments{/number}",
	  "contents_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/contents/{+path}",
	  "compare_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/compare/{base}...{head}",
	  "merges_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/merges",
	  "archive_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/{archive_format}{/ref}",
	  "downloads_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/downloads",
	  "issues_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/issues{/number}",
	  "pulls_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/pulls{/number}",
	  "milestones_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/milestones{/number}",
	  "notifications_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/notifications{?since,all,participating}",
	  "labels_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/labels{/name}",
	  "releases_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/releases{/id}",
	  "deployments_url": "https://api.github.com/repos/asa-dillahunty/CS300-Project/deployments",
	  "created_at": "2020-03-28T06:39:19Z",
	  "updated_at": "2020-06-20T01:24:41Z",
	  "pushed_at": "2020-04-03T21:56:43Z",
	  "git_url": "git://github.com/asa-dillahunty/CS300-Project.git",
	  "ssh_url": "git@github.com:asa-dillahunty/CS300-Project.git",
	  "clone_url": "https://github.com/asa-dillahunty/CS300-Project.git",
	  "svn_url": "https://github.com/asa-dillahunty/CS300-Project",
	  "homepage": null,
	  "size": 8160,
	  "stargazers_count": 0,
	  "watchers_count": 0,
	  "language": "C",
	  "has_issues": true,
	  "has_projects": true,
	  "has_downloads": true,
	  "has_wiki": true,
	  "has_pages": false,
	  "forks_count": 0,
	  "mirror_url": null,
	  "archived": false,
	  "disabled": false,
	  "open_issues_count": 0,
	  "license": null,
	  "forks": 0,
	  "open_issues": 0,
	  "watchers": 0,
	  "default_branch": "master"
	},
	{
	  "id": 309892627,
	  "node_id": "MDEwOlJlcG9zaXRvcnkzMDk4OTI2Mjc=",
	  "name": "Maze-Generation-and-Solving",
	  "full_name": "asa-dillahunty/Maze-Generation-and-Solving",
	  "private": false,
	  "owner": {
		"login": "asa-dillahunty",
		"id": 28574798,
		"node_id": "MDQ6VXNlcjI4NTc0Nzk4",
		"avatar_url": "https://avatars.githubusercontent.com/u/28574798?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/asa-dillahunty",
		"html_url": "https://github.com/asa-dillahunty",
		"followers_url": "https://api.github.com/users/asa-dillahunty/followers",
		"following_url": "https://api.github.com/users/asa-dillahunty/following{/other_user}",
		"gists_url": "https://api.github.com/users/asa-dillahunty/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/asa-dillahunty/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/asa-dillahunty/subscriptions",
		"organizations_url": "https://api.github.com/users/asa-dillahunty/orgs",
		"repos_url": "https://api.github.com/users/asa-dillahunty/repos",
		"events_url": "https://api.github.com/users/asa-dillahunty/events{/privacy}",
		"received_events_url": "https://api.github.com/users/asa-dillahunty/received_events",
		"type": "User",
		"site_admin": false
	  },
	  "html_url": "https://github.com/asa-dillahunty/Maze-Generation-and-Solving",
	  "description": "Maze generation using Prim's algorithm or recursive backtracking, then solving them using recursive backtracking.",
	  "fork": false,
	  "url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving",
	  "forks_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/forks",
	  "keys_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/keys{/key_id}",
	  "collaborators_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/collaborators{/collaborator}",
	  "teams_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/teams",
	  "hooks_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/hooks",
	  "issue_events_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/issues/events{/number}",
	  "events_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/events",
	  "assignees_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/assignees{/user}",
	  "branches_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/branches{/branch}",
	  "tags_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/tags",
	  "blobs_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/git/blobs{/sha}",
	  "git_tags_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/git/tags{/sha}",
	  "git_refs_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/git/refs{/sha}",
	  "trees_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/git/trees{/sha}",
	  "statuses_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/statuses/{sha}",
	  "languages_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/languages",
	  "stargazers_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/stargazers",
	  "contributors_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/contributors",
	  "subscribers_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/subscribers",
	  "subscription_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/subscription",
	  "commits_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/commits{/sha}",
	  "git_commits_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/git/commits{/sha}",
	  "comments_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/comments{/number}",
	  "issue_comment_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/issues/comments{/number}",
	  "contents_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/contents/{+path}",
	  "compare_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/compare/{base}...{head}",
	  "merges_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/merges",
	  "archive_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/{archive_format}{/ref}",
	  "downloads_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/downloads",
	  "issues_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/issues{/number}",
	  "pulls_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/pulls{/number}",
	  "milestones_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/milestones{/number}",
	  "notifications_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/notifications{?since,all,participating}",
	  "labels_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/labels{/name}",
	  "releases_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/releases{/id}",
	  "deployments_url": "https://api.github.com/repos/asa-dillahunty/Maze-Generation-and-Solving/deployments",
	  "created_at": "2020-11-04T05:02:11Z",
	  "updated_at": "2020-11-22T06:39:03Z",
	  "pushed_at": "2020-11-22T06:39:01Z",
	  "git_url": "git://github.com/asa-dillahunty/Maze-Generation-and-Solving.git",
	  "ssh_url": "git@github.com:asa-dillahunty/Maze-Generation-and-Solving.git",
	  "clone_url": "https://github.com/asa-dillahunty/Maze-Generation-and-Solving.git",
	  "svn_url": "https://github.com/asa-dillahunty/Maze-Generation-and-Solving",
	  "homepage": null,
	  "size": 27,
	  "stargazers_count": 0,
	  "watchers_count": 0,
	  "language": "Java",
	  "has_issues": true,
	  "has_projects": true,
	  "has_downloads": true,
	  "has_wiki": true,
	  "has_pages": true,
	  "forks_count": 0,
	  "mirror_url": null,
	  "archived": false,
	  "disabled": false,
	  "open_issues_count": 0,
	  "license": null,
	  "forks": 0,
	  "open_issues": 0,
	  "watchers": 0,
	  "default_branch": "master"
	},
	{
	  "id": 241167685,
	  "node_id": "MDEwOlJlcG9zaXRvcnkyNDExNjc2ODU=",
	  "name": "QubicTicTacToe",
	  "full_name": "asa-dillahunty/QubicTicTacToe",
	  "private": false,
	  "owner": {
		"login": "asa-dillahunty",
		"id": 28574798,
		"node_id": "MDQ6VXNlcjI4NTc0Nzk4",
		"avatar_url": "https://avatars.githubusercontent.com/u/28574798?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/asa-dillahunty",
		"html_url": "https://github.com/asa-dillahunty",
		"followers_url": "https://api.github.com/users/asa-dillahunty/followers",
		"following_url": "https://api.github.com/users/asa-dillahunty/following{/other_user}",
		"gists_url": "https://api.github.com/users/asa-dillahunty/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/asa-dillahunty/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/asa-dillahunty/subscriptions",
		"organizations_url": "https://api.github.com/users/asa-dillahunty/orgs",
		"repos_url": "https://api.github.com/users/asa-dillahunty/repos",
		"events_url": "https://api.github.com/users/asa-dillahunty/events{/privacy}",
		"received_events_url": "https://api.github.com/users/asa-dillahunty/received_events",
		"type": "User",
		"site_admin": false
	  },
	  "html_url": "https://github.com/asa-dillahunty/QubicTicTacToe",
	  "description": "Tic Tac Toe in 3D",
	  "fork": false,
	  "url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe",
	  "forks_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/forks",
	  "keys_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/keys{/key_id}",
	  "collaborators_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/collaborators{/collaborator}",
	  "teams_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/teams",
	  "hooks_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/hooks",
	  "issue_events_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/issues/events{/number}",
	  "events_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/events",
	  "assignees_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/assignees{/user}",
	  "branches_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/branches{/branch}",
	  "tags_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/tags",
	  "blobs_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/git/blobs{/sha}",
	  "git_tags_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/git/tags{/sha}",
	  "git_refs_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/git/refs{/sha}",
	  "trees_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/git/trees{/sha}",
	  "statuses_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/statuses/{sha}",
	  "languages_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/languages",
	  "stargazers_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/stargazers",
	  "contributors_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/contributors",
	  "subscribers_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/subscribers",
	  "subscription_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/subscription",
	  "commits_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/commits{/sha}",
	  "git_commits_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/git/commits{/sha}",
	  "comments_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/comments{/number}",
	  "issue_comment_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/issues/comments{/number}",
	  "contents_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/contents/{+path}",
	  "compare_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/compare/{base}...{head}",
	  "merges_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/merges",
	  "archive_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/{archive_format}{/ref}",
	  "downloads_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/downloads",
	  "issues_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/issues{/number}",
	  "pulls_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/pulls{/number}",
	  "milestones_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/milestones{/number}",
	  "notifications_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/notifications{?since,all,participating}",
	  "labels_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/labels{/name}",
	  "releases_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/releases{/id}",
	  "deployments_url": "https://api.github.com/repos/asa-dillahunty/QubicTicTacToe/deployments",
	  "created_at": "2020-02-17T17:29:06Z",
	  "updated_at": "2021-05-08T22:12:13Z",
	  "pushed_at": "2021-05-08T22:12:10Z",
	  "git_url": "git://github.com/asa-dillahunty/QubicTicTacToe.git",
	  "ssh_url": "git@github.com:asa-dillahunty/QubicTicTacToe.git",
	  "clone_url": "https://github.com/asa-dillahunty/QubicTicTacToe.git",
	  "svn_url": "https://github.com/asa-dillahunty/QubicTicTacToe",
	  "homepage": null,
	  "size": 1453,
	  "stargazers_count": 0,
	  "watchers_count": 0,
	  "language": "Java",
	  "has_issues": true,
	  "has_projects": true,
	  "has_downloads": true,
	  "has_wiki": true,
	  "has_pages": true,
	  "forks_count": 0,
	  "mirror_url": null,
	  "archived": false,
	  "disabled": false,
	  "open_issues_count": 0,
	  "license": null,
	  "forks": 0,
	  "open_issues": 0,
	  "watchers": 0,
	  "default_branch": "master"
	},
	{
	  "id": 299415121,
	  "node_id": "MDEwOlJlcG9zaXRvcnkyOTk0MTUxMjE=",
	  "name": "twitchbot",
	  "full_name": "asa-dillahunty/twitchbot",
	  "private": false,
	  "owner": {
		"login": "asa-dillahunty",
		"id": 28574798,
		"node_id": "MDQ6VXNlcjI4NTc0Nzk4",
		"avatar_url": "https://avatars.githubusercontent.com/u/28574798?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/asa-dillahunty",
		"html_url": "https://github.com/asa-dillahunty",
		"followers_url": "https://api.github.com/users/asa-dillahunty/followers",
		"following_url": "https://api.github.com/users/asa-dillahunty/following{/other_user}",
		"gists_url": "https://api.github.com/users/asa-dillahunty/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/asa-dillahunty/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/asa-dillahunty/subscriptions",
		"organizations_url": "https://api.github.com/users/asa-dillahunty/orgs",
		"repos_url": "https://api.github.com/users/asa-dillahunty/repos",
		"events_url": "https://api.github.com/users/asa-dillahunty/events{/privacy}",
		"received_events_url": "https://api.github.com/users/asa-dillahunty/received_events",
		"type": "User",
		"site_admin": false
	  },
	  "html_url": "https://github.com/asa-dillahunty/twitchbot",
	  "description": "A very simple twitch bot that allows for interaction with the chat",
	  "fork": false,
	  "url": "https://api.github.com/repos/asa-dillahunty/twitchbot",
	  "forks_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/forks",
	  "keys_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/keys{/key_id}",
	  "collaborators_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/collaborators{/collaborator}",
	  "teams_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/teams",
	  "hooks_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/hooks",
	  "issue_events_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/issues/events{/number}",
	  "events_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/events",
	  "assignees_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/assignees{/user}",
	  "branches_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/branches{/branch}",
	  "tags_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/tags",
	  "blobs_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/git/blobs{/sha}",
	  "git_tags_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/git/tags{/sha}",
	  "git_refs_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/git/refs{/sha}",
	  "trees_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/git/trees{/sha}",
	  "statuses_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/statuses/{sha}",
	  "languages_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/languages",
	  "stargazers_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/stargazers",
	  "contributors_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/contributors",
	  "subscribers_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/subscribers",
	  "subscription_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/subscription",
	  "commits_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/commits{/sha}",
	  "git_commits_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/git/commits{/sha}",
	  "comments_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/comments{/number}",
	  "issue_comment_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/issues/comments{/number}",
	  "contents_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/contents/{+path}",
	  "compare_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/compare/{base}...{head}",
	  "merges_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/merges",
	  "archive_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/{archive_format}{/ref}",
	  "downloads_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/downloads",
	  "issues_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/issues{/number}",
	  "pulls_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/pulls{/number}",
	  "milestones_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/milestones{/number}",
	  "notifications_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/notifications{?since,all,participating}",
	  "labels_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/labels{/name}",
	  "releases_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/releases{/id}",
	  "deployments_url": "https://api.github.com/repos/asa-dillahunty/twitchbot/deployments",
	  "created_at": "2020-09-28T19:45:47Z",
	  "updated_at": "2020-10-14T11:13:38Z",
	  "pushed_at": "2020-11-13T21:06:14Z",
	  "git_url": "git://github.com/asa-dillahunty/twitchbot.git",
	  "ssh_url": "git@github.com:asa-dillahunty/twitchbot.git",
	  "clone_url": "https://github.com/asa-dillahunty/twitchbot.git",
	  "svn_url": "https://github.com/asa-dillahunty/twitchbot",
	  "homepage": null,
	  "size": 14,
	  "stargazers_count": 0,
	  "watchers_count": 0,
	  "language": "JavaScript",
	  "has_issues": true,
	  "has_projects": true,
	  "has_downloads": true,
	  "has_wiki": true,
	  "has_pages": false,
	  "forks_count": 0,
	  "mirror_url": null,
	  "archived": false,
	  "disabled": false,
	  "open_issues_count": 0,
	  "license": null,
	  "forks": 0,
	  "open_issues": 0,
	  "watchers": 0,
	  "default_branch": "master"
	},
	{
	  "id": 241180270,
	  "node_id": "MDEwOlJlcG9zaXRvcnkyNDExODAyNzA=",
	  "name": "VariableConnect4",
	  "full_name": "asa-dillahunty/VariableConnect4",
	  "private": false,
	  "owner": {
		"login": "asa-dillahunty",
		"id": 28574798,
		"node_id": "MDQ6VXNlcjI4NTc0Nzk4",
		"avatar_url": "https://avatars.githubusercontent.com/u/28574798?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/asa-dillahunty",
		"html_url": "https://github.com/asa-dillahunty",
		"followers_url": "https://api.github.com/users/asa-dillahunty/followers",
		"following_url": "https://api.github.com/users/asa-dillahunty/following{/other_user}",
		"gists_url": "https://api.github.com/users/asa-dillahunty/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/asa-dillahunty/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/asa-dillahunty/subscriptions",
		"organizations_url": "https://api.github.com/users/asa-dillahunty/orgs",
		"repos_url": "https://api.github.com/users/asa-dillahunty/repos",
		"events_url": "https://api.github.com/users/asa-dillahunty/events{/privacy}",
		"received_events_url": "https://api.github.com/users/asa-dillahunty/received_events",
		"type": "User",
		"site_admin": false
	  },
	  "html_url": "https://github.com/asa-dillahunty/VariableConnect4",
	  "description": "Connect 4, but the size of the board is variable.",
	  "fork": false,
	  "url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4",
	  "forks_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/forks",
	  "keys_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/keys{/key_id}",
	  "collaborators_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/collaborators{/collaborator}",
	  "teams_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/teams",
	  "hooks_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/hooks",
	  "issue_events_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/issues/events{/number}",
	  "events_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/events",
	  "assignees_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/assignees{/user}",
	  "branches_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/branches{/branch}",
	  "tags_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/tags",
	  "blobs_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/git/blobs{/sha}",
	  "git_tags_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/git/tags{/sha}",
	  "git_refs_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/git/refs{/sha}",
	  "trees_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/git/trees{/sha}",
	  "statuses_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/statuses/{sha}",
	  "languages_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/languages",
	  "stargazers_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/stargazers",
	  "contributors_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/contributors",
	  "subscribers_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/subscribers",
	  "subscription_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/subscription",
	  "commits_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/commits{/sha}",
	  "git_commits_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/git/commits{/sha}",
	  "comments_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/comments{/number}",
	  "issue_comment_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/issues/comments{/number}",
	  "contents_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/contents/{+path}",
	  "compare_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/compare/{base}...{head}",
	  "merges_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/merges",
	  "archive_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/{archive_format}{/ref}",
	  "downloads_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/downloads",
	  "issues_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/issues{/number}",
	  "pulls_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/pulls{/number}",
	  "milestones_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/milestones{/number}",
	  "notifications_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/notifications{?since,all,participating}",
	  "labels_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/labels{/name}",
	  "releases_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/releases{/id}",
	  "deployments_url": "https://api.github.com/repos/asa-dillahunty/VariableConnect4/deployments",
	  "created_at": "2020-02-17T18:35:40Z",
	  "updated_at": "2020-02-17T18:41:02Z",
	  "pushed_at": "2020-02-17T18:41:00Z",
	  "git_url": "git://github.com/asa-dillahunty/VariableConnect4.git",
	  "ssh_url": "git@github.com:asa-dillahunty/VariableConnect4.git",
	  "clone_url": "https://github.com/asa-dillahunty/VariableConnect4.git",
	  "svn_url": "https://github.com/asa-dillahunty/VariableConnect4",
	  "homepage": null,
	  "size": 8,
	  "stargazers_count": 0,
	  "watchers_count": 0,
	  "language": "C",
	  "has_issues": true,
	  "has_projects": true,
	  "has_downloads": true,
	  "has_wiki": true,
	  "has_pages": false,
	  "forks_count": 0,
	  "mirror_url": null,
	  "archived": false,
	  "disabled": false,
	  "open_issues_count": 0,
	  "license": null,
	  "forks": 0,
	  "open_issues": 0,
	  "watchers": 0,
	  "default_branch": "master"
	}
  ]




let currUserData = null;
let currRepoData = null;
// console.log(example_data2.length);
// console.log(example_data2[2]);

// logData(example_data["repos_url"]);
// logData("https://api.github.com/repos/asa-dillahunty/asa-dillahunty.github.io/contributors");

document.getElementById("github-search").addEventListener("click", () => {
	let val = document.getElementById("github-username").value;
	console.log(val);
	// setUserData(example_data, example_data2);
	getUserRepos(val);
});


function logData(url) {
	console.log(url);
	
	var request = new XMLHttpRequest();
	request.open('get', url);
	request.onreadystatechange = () => {
		if (request.readyState == 4)
			console.log(request.response);

		console.log(request.readyState);
	}
	request.send();
}

function getUserRepos(username) {
	var request = new XMLHttpRequest();
	request.open('get',`https://api.github.com/users/${username}`);
	request.onreadystatechange = () => {
		if (request.readyState === 4) {
			if (request.status === 404) {
				console.log('not found');
				setUserData(null,null);
			}
			else {
				currUserData = JSON.parse(request.response);
				getUserRepos2(currUserData.repos_url);
			}
		}

		// console.log(request.readyState);
	}
	request.send();
}

function getUserRepos2(url) {
	var request = new XMLHttpRequest();
	request.open('get', url);
	request.onreadystatechange = () => {
		if (request.readyState === 4) {
			if (request.status === 404) {
				console.log('not found');
				setUserData(null,null);
			}
			else {
				currRepoData = JSON.parse(request.response);

				// userdata needs to be an object, repo data needs to be an array
				setUserData(currUserData,currRepoData);
			}
		}

		// console.log(request.readyState);
	}
	request.send();
}

function getGitData() {
	var request = new XMLHttpRequest();
	request.open('get','https://api.github.com/users/asa-dillahunty');
	request.onreadystatechange = () => {
		if (request.readyState == 4)
			console.log(request.response);

		console.log(request.readyState);
	}
	request.send();
}


function setUserData(userData, repoData) {
	if (!userData) {
		userData = {
			name:"User's Name",
			login:"username",
			avatar_url:"assets/person.png",
		};
		repoData = [];
	}
	// name
	// html_url
	// login (username)
	// bio (if has)
	// avatar_url
	document.getElementById("user's name").textContent = userData["name"];
	document.getElementById("username").textContent = userData['login'];
	document.getElementById("user-pfp").src = userData["avatar_url"];

	// remove past repos
	let repoParent = document.getElementById("repo-field");
	while (repoParent.hasChildNodes()) {
		repoParent.removeChild(repoParent.firstChild);
	}

	// add current repos
	// name
	// html_url
	// description
	// language
	// forks
	// stargazers_count
	// some repos will have social previews (how get?)
	repoData.forEach( (elem) => {

		// if (elem.fork) return;

		repoParent.insertAdjacentHTML('beforeend', 
			`<div class="repo">
				<div class="repo-top-info">
					<p class="repo-title">${elem['name']}</p>
					<div class="repo-tags">
						<div class="repo-tag">
							${ elem["forks_count"] ? elem['forks_count'] : 0}
							<i class="fas fa-code-branch"></i>
						</div>
						<div class="repo-tag">
							${ elem["stargazers_count"] ? elem['stargazers_count'] : 0}
							<i class="fas fa-star"></i>
						</div>
					</div>
				</div>
				<p class="repo-description">${elem["description"] ? elem["description"] : "" }
			</div>`
		);
		
		console.log(elem['name']);
		console.log(elem['html_url']);
	});
}